pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "nesa24/myrepo"
        AWS_REGION = "us-east-1"
        CLUSTER_NAME = "my-eks-cluster"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Satheeshshyam/Devops.git', branch: 'main'
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                dir('terraform-aws-3tier-architecture') {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                    sh 'terraform output'
                }
            }
        }

        stage('Configure kubeconfig') {
            steps {
                sh """
                aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
                kubectl config current-context
                """
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE -f jenkins_ci-cd/Dockerfile .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                credentialsId: 'dockerhub-pass',
                usernameVariable: 'USER',
                passwordVariable: 'PASS'
                )]) {
                sh '''
                echo $PASS | docker login -u $USER --password-stdin
                docker push $DOCKER_IMAGE
                '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps 
            {
                dir('kubernetes-microservices') 
                {
                    sh 'kubectl apply -f deployment.yaml'
                    sh 'kubectl apply -f service.yaml'
                    sh 'kubectl apply -f ingress.yaml'
                }
            }
        }
    }
}
