pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "nesa24/myrepo"
    }

    stages {
        
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE -f jenkins_ci-cd/Dockerfile .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                credentialsId: 'dockerhub-pass',
                usernameVariable: 'USER',
                passwordVariable: 'PASS'
                )]) {
                sh '''
                echo $PASS | docker login -u $USER --password-stdin
                docker push $DOCKER_IMAGE
                '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f jenkins_ci-cd/kubernetes/deployment.yaml'
            }
        }

    }
}
